### ISSUE TITLE
Snapshots do not handle new CDROM tweaks

### ISSUE THREAD

**Issue by mikalstill** [mikalstill/shakenfist#27]
```
# sf-client instance snapshot 4dae894a-3f89-4c7d-b8eb-04d890cf0d5d
Traceback (most recent call last):
  File "/usr/local/bin/sf-client", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/shakenfist/src/shakenfist/client/main.py", line 473, in instance_snapshot
    uuid = CLIENT.snapshot_instance(instance_uuid, all)
  File "/srv/shakenfist/src/shakenfist/client/apiclient.py", line 83, in snapshot_instance
    '/snapshot', data={'all': all})
  File "/srv/shakenfist/src/shakenfist/client/apiclient.py", line 45, in _request_url
    'API request failed', method, url, r.status_code, r.text)
shakenfist.client.apiclient.APIException: ('API request failed', 'POST', 'http://localhost:13000/instances/4dae894a-3f89-4c7d-b8eb-04d890cf0d5d/snapshot', 500, '{"error": "server error", "status": 500, "traceback": "Traceback (most recent call last):\\n  File \\"/srv/shakenfist/src/shakenfist/daemons/external_api.py\\", line 56, in wrapper\\n    return func(*args, **kwargs)\\n  File \\"/srv/shakenfist/src/shakenfist/daemons/external_api.py\\", line 89, in wrapper\\n    return func(*args, **kwargs)\\n  File \\"/srv/shakenfist/src/shakenfist/daemons/external_api.py\\", line 113, in wrapper\\n    return func(*args, **kwargs)\\n  File \\"/srv/shakenfist/src/shakenfist/daemons/external_api.py\\", line 319, in post\\n    snap_uuid = instance_from_db_virt.snapshot(all=args[\'all\'])\\n  File \\"/srv/shakenfist/src/shakenfist/virt.py\\", line 425, in snapshot\\n    d[\'path\'], os.path.join(snappath, d[\'device\']))\\n  File \\"/srv/shakenfist/src/shakenfist/virt.py\\", line 402, in _snapshot_device\\n    images.snapshot(source, destination)\\n  File \\"/srv/shakenfist/src/shakenfist/images.py\\", line 212, in snapshot\\n    shell=True)\\n  File \\"/usr/local/lib/python3.6/dist-packages/oslo_concurrency/processutils.py\\", line 424, in execute\\n    cmd=sanitized_cmd)\\noslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.\\nCommand: qemu-img convert --force-share -O qcow2 /srv/shakenfist/instances/4dae894a-3f89-4c7d-b8eb-04d890cf0d5d/vdc.qcow2 /srv/shakenfist/snapshots/dc498e79-974a-49f8-a776-d0cc7f5b2f31/vdc\\nExit code: 1\\nStdout: \'\'\\nStderr: \\"qemu-img: Could not open \'/srv/shakenfist/instances/4dae894a-3f89-4c7d-b8eb-04d890cf0d5d/vdc.qcow2\': Could not open \'/srv/shakenfist/instances/4dae894a-3f89-4c7d-b8eb-04d890cf0d5d/vdc.qcow2\': No such file or directory\\\\n\\"\\n"}')
```

I shouldn't be trying to snapshot CDROMs anyways.

**Comment by mikalstill** [comment]
Commit 81d8e2994991081a5c4637294cf8d5c5e3dde5cd adds a test which shows this works right.
