### ISSUE TITLE
Creating an instance with no network causes a crash

### ISSUE THREAD

**Issue by mikalstill** [mikalstill/shakenfist#29]
```
# sf-client instance create cirros 1 1 -d 8@cirros
Traceback (most recent call last):
  File "/usr/local/bin/sf-client", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/shakenfist/src/shakenfist/client/main.py", line 405, in instance_create
    network, disk, sshkey_content, userdata_content))
  File "/srv/shakenfist/src/shakenfist/client/apiclient.py", line 77, in create_instance
    'user_data': userdata
  File "/srv/shakenfist/src/shakenfist/client/apiclient.py", line 45, in _request_url
    'API request failed', method, url, r.status_code, r.text)
shakenfist.client.apiclient.APIException: ('API request failed', 'POST', 'http://localhost:13000/instances', 500, '{"error": "server error", "status": 500, "traceback": "Traceback (most recent call last):\\n  File \\"/srv/shakenfist/src/shakenfist/daemons/external_api.py\\", line 56, in wrapper\\n    return func(*args, **kwargs)\\n  File \\"/srv/shakenfist/src/shakenfist/daemons/external_api.py\\", line 245, in post\\n    for network in args[\'network\']:\\nTypeError: \'NoneType\' object is not iterable\\n"}')
```

**Comment by mikalstill** [comment]
I've added a test for this and it now works.
